import React, { useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  KeyboardAvoidingView,
  Platform,
  Alert,
} from "react-native";
import { NativeStackScreenProps } from "@react-navigation/native-stack";
import { Ionicons } from "@expo/vector-icons";
import { RootStackParamList } from "../../types/navigation";
import { useAuth } from "../../context/AuthContext";
import { useTheme } from "../../context/ThemeContext";
import { Input } from "../../components/common/Input";
import { Button } from "../../components/common/Button";
import { getApiErrorMessage } from "../../api/client";

type Props = NativeStackScreenProps<RootStackParamList, "Login">;

export const LoginScreen: React.FC<Props> = ({ route, navigation }) => {
  const { colors, isDark } = useTheme();
  const { login } = useAuth();

  const [email, setEmail] = useState(route.params?.prefillEmail || "");
  const [password, setPassword] = useState("");
  const [mfaCode, setMfaCode] = useState("");
  const [showMfaInput, setShowMfaInput] = useState(false);
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const validate = () => {
    const nextErrors: Record<string, string> = {};
    if (!email.trim()) {
      nextErrors.email = "Email is required";
    } else if (!/\S+@\S+\.\S+/.test(email)) {
      nextErrors.email = "Please enter a valid email address";
    }
    if (!password) {
      nextErrors.password = "Password is required";
    }
    if (showMfaInput && (!mfaCode.trim() || mfaCode.trim().length !== 6)) {
      nextErrors.mfa = "Please enter the 6-digit MFA code";
    }
    setErrors(nextErrors);
    return Object.keys(nextErrors).length === 0;
  };

  const handleLogin = async () => {
    if (!validate()) return;

    setLoading(true);
    try {
      await login(
        email.trim().toLowerCase(),
        password,
        showMfaInput ? mfaCode.trim() : undefined
      );
      // Navigation is automatically handled or replace to MainTabs
      navigation.replace("MainTabs");
    } catch (err: any) {
      const msg = getApiErrorMessage(err);
      if (
        msg.includes("MFA code required") ||
        err.response?.data?.detail?.includes("MFA code required")
      ) {
        setShowMfaInput(true);
        Alert.alert(
          "Two-Factor Authentication Required",
          "Please enter the 6-digit TOTP code generated by your authenticator app."
        );
      } else if (
        msg.includes("temporarily locked") ||
        err.response?.status === 403
      ) {
        Alert.alert(
          "Account Locked",
          "This account has been temporarily locked due to repeated failed login attempts. Please try again in 15 minutes."
        );
      } else {
        Alert.alert("Login Failed", msg);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <KeyboardAvoidingView
      behavior={Platform.OS === "ios" ? "padding" : undefined}
      style={[styles.container, { backgroundColor: colors.background }]}
    >
      <ScrollView
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Logo / Header */}
        <View style={styles.header}>
          <View
            style={[
              styles.logoCircle,
              {
                backgroundColor: colors.cardSecondary,
                borderColor: colors.border,
              },
            ]}
          >
            <Ionicons name="heart" size={36} color={colors.primary} />
          </View>
          <Text style={[styles.title, { color: colors.textPrimary }]}>Welcome Back</Text>
          <Text style={[styles.subtitle, { color: colors.textSecondary }]}>
            Sign in to access your blood response portal
          </Text>
        </View>

        {/* Input Fields */}
        <Input
          label="Email Address"
          placeholder="name@example.com"
          keyboardType="email-address"
          autoCapitalize="none"
          value={email}
          onChangeText={setEmail}
          error={errors.email}
          leftIcon={
            <Ionicons name="mail-outline" size={18} color={colors.iconMuted} />
          }
        />

        <Input
          label="Password"
          placeholder="••••••••"
          secureTextEntry
          value={password}
          onChangeText={setPassword}
          error={errors.password}
          leftIcon={
            <Ionicons name="lock-closed-outline" size={18} color={colors.iconMuted} />
          }
        />

        {showMfaInput ? (
          <Input
            label="MFA Authenticator Code"
            placeholder="123456"
            keyboardType="number-pad"
            maxLength={6}
            value={mfaCode}
            onChangeText={setMfaCode}
            error={errors.mfa}
            leftIcon={
              <Ionicons name="key-outline" size={18} color={colors.iconMuted} />
            }
          />
        ) : null}

        {/* Forgot Password */}
        <TouchableOpacity
          activeOpacity={0.7}
          onPress={() =>
            Alert.alert(
              "Reset Password",
              "Password reset instructions have been forwarded to your system administrator."
            )
          }
          style={styles.forgotPassContainer}
        >
          <Text style={[styles.forgotPassText, { color: colors.primary }]}>
            Forgot password?
          </Text>
        </TouchableOpacity>

        {/* Login Button */}
        <Button
          title={showMfaInput ? "Verify & Log In" : "Sign In"}
          onPress={handleLogin}
          loading={loading}
          size="lg"
          style={styles.submitButton}
        />

        {/* Quick Demo Logins Helper */}
        <View
          style={[
            styles.demoBox,
            {
              backgroundColor: colors.cardSecondary,
              borderColor: colors.borderLight,
            },
          ]}
        >
          <Text style={[styles.demoTitle, { color: colors.textPrimary }]}>
            Quick Fill For Testing:
          </Text>
          <View style={styles.demoButtonsRow}>
            <TouchableOpacity
              onPress={() => {
                setEmail("donor1@test.com");
                setPassword("password123");
              }}
              style={[styles.demoChip, { borderColor: colors.border }]}
            >
              <Text style={[styles.demoChipText, { color: colors.primary }]}>
                Donor
              </Text>
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => {
                setEmail("patient1@test.com");
                setPassword("password123");
              }}
              style={[styles.demoChip, { borderColor: colors.border }]}
            >
              <Text style={[styles.demoChipText, { color: colors.primary }]}>
                Patient
              </Text>
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => {
                setEmail("admin1@test.com");
                setPassword("password123");
              }}
              style={[styles.demoChip, { borderColor: colors.border }]}
            >
              <Text style={[styles.demoChipText, { color: colors.primary }]}>
                Admin
              </Text>
            </TouchableOpacity>
          </View>
        </View>

        {/* Register Prompt */}
        <View style={styles.footerRow}>
          <Text style={[styles.footerPrompt, { color: colors.textSecondary }]}>
            Don't have an account?{" "}
          </Text>
          <TouchableOpacity onPress={() => navigation.navigate("Register")}>
            <Text style={[styles.footerLink, { color: colors.primary }]}>
              Register Now
            </Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </KeyboardAvoidingView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 64,
    paddingBottom: 40,
  },
  header: {
    alignItems: "center",
    marginBottom: 32,
  },
  logoCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    marginBottom: 16,
    shadowColor: "#E63950",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2,
  },
  title: {
    fontSize: 26,
    fontWeight: "800",
    marginBottom: 6,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  forgotPassContainer: {
    alignSelf: "flex-end",
    marginBottom: 20,
  },
  forgotPassText: {
    fontSize: 13,
    fontWeight: "600",
  },
  submitButton: {
    marginBottom: 24,
  },
  demoBox: {
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    marginBottom: 24,
  },
  demoTitle: {
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 8,
    textTransform: "uppercase",
  },
  demoButtonsRow: {
    flexDirection: "row",
    gap: 8,
  },
  demoChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    backgroundColor: "transparent",
  },
  demoChipText: {
    fontSize: 12,
    fontWeight: "600",
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  footerPrompt: {
    fontSize: 14,
  },
  footerLink: {
    fontSize: 14,
    fontWeight: "700",
  },
});
